# 以下は実際は別管理のリポジトリに保存することを推奨 (Terraformのリポジトリ など)
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: sample-springboot-cloudrun-deployment
description: pipeline to deploy sample-springboot-cloudrun
serialPipeline:
  stages:
  - targetId: run-dev
    profiles: [dev]
    strategy:
      standard:
        verify: true
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-dev
description: Cloud Run service in dev environment
requireApproval: true
run:
  location: projects/<GCP_PROJECT>/locations/<GCP_REGION>
executionConfigs:
- usages: ["RENDER", "DEPLOY"]
  serviceAccount: <CUSTOM_EXECUTION_SERVICE_ACCOUNT>@<GCP_PROJECT>.iam.gserviceaccount.com
- usages: ["PREDEPLOY", "VERIFY", "POSTDEPLOY"]
