apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld
spec:
  template:
    spec:
      containers:
      - image: sample-springboot-cloudrun-image
        ports:
          - containerPort: 8080
