apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: deploy-cloudrun
profiles:
- name: dev
  manifests:
    rawYaml:
    - service.yaml
deploy:
  cloudrun: {}
verify:
- name: verification-test # スモークテストのサンプル
  container:
    name: verification-echo
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", 'echo "Your test or tests would go here."' ] # TODO: サービスへのHTTPリクエストに変更する
